DROP DATABASE IF EXISTS LBC;
CREATE DATABASE IF NOT EXISTS LBC;
USE LBC;


CREATE TABLE USUARIO(
    ID_Usuario INT AUTO_INCREMENT,
    Nickname VARCHAR(255) NOT NULL UNIQUE,
    Contraseña VARCHAR(255),
    Fecha_Nac DATE,
    Correo VARCHAR(255),
    País VARCHAR(255),
    Rango INT,
    PRIMARY KEY (ID_Usuario)
);

CREATE TABLE EQUIPO(
    ID_Equipo INT AUTO_INCREMENT,
    Nombre VARCHAR(255) NOT NULL UNIQUE,
    Fecha DATE,
    Victorias INT,
    Derrotas INT,
    Media FLOAT,
    PRIMARY KEY (ID_Equipo)
);

CREATE TABLE JUEGO(
    ID_Juego INT AUTO_INCREMENT,
    Nombre VARCHAR(255),
    Descripcion VARCHAR(500),
    Tipo INT,
    PRIMARY KEY (ID_Juego)
);

CREATE TABLE TORNEO(
    ID_Torneo INT AUTO_INCREMENT,
    Nombre VARCHAR(255),
    ID_Juego INT,
    Cantidad INT,
    Fecha DATE,
    Premio VARCHAR(255),
    Ganador INT,
    PRIMARY KEY (ID_Torneo)
);

CREATE TABLE PARTIDO(
    ID_Partido INT AUTO_INCREMENT,
    ID_Visitante INT,
    ID_Local INT,
    Resultado_Visitante INT,
    Resultado_Local INT,
    Fecha DATE,
    PRIMARY KEY (ID_Partido)
);

CREATE TABLE LIGA(
    ID_Liga INT AUTO_INCREMENT,
    Nombre VARCHAR(255),
    Pais VARCHAR(255),
    PRIMARY KEY (ID_Liga)
);

CREATE TABLE RANGO(
    ID_Rango INT AUTO_INCREMENT,
    Nombre VARCHAR(255),
    Descripcion VARCHAR(500),
    PRIMARY KEY (ID_Rango)
);

CREATE TABLE AMONESTACION(
    ID_Amonestacion INT AUTO_INCREMENT,
    Gravedad VARCHAR(255),
    Duracion DATETIME,
    PRIMARY KEY (ID_Amonestacion)
);

CREATE TABLE RONDA(
    ID_Ronda INT AUTO_INCREMENT,
    Nombre VARCHAR(255),
    PRIMARY KEY (ID_Ronda)
);

CREATE TABLE BANEO(
    ID_Usuario INT,
    ID_Amonestacion INT,
    Fecha_DesBan DATETIME
);

CREATE TABLE PARTIDO_TORNEO(
    ID_Partido INT,
    ID_Torneo INT,
    ID_Ronda INT
);

CREATE TABLE EQUIPO_TORNEO(
    ID_Equipo INT,
    ID_Torneo INT
);

CREATE TABLE USUARIO_EQUIPO(
    ID_Equipo INT,
    ID_Usuario INT
);

CREATE TABLE PARTIDO_LIGA(
    ID_Partido INT,
    ID_Liga INT
);

CREATE TABLE EQUIPO_LIGA(
	ID_Equipo INT,
    ID_Liga INT
);

CREATE TABLE TIPO(
    ID_Tipo INT AUTO_INCREMENT,
    Nombre VARCHAR(255),
    PRIMARY KEY (ID_Tipo)
);

CREATE TABLE PAGINA_WEB(
    ID_Web INT AUTO_INCREMENT,
    Nombre VARCHAR(255),
    URL VARCHAR(255),
    PRIMARY KEY (ID_Web)
);


ALTER TABLE TORNEO
ADD FOREIGN KEY (ID_Juego) REFERENCES JUEGO(ID_Juego);

ALTER TABLE TORNEO
ADD FOREIGN KEY (Ganador) REFERENCES EQUIPO(ID_Equipo);

ALTER TABLE PARTIDO
ADD FOREIGN KEY (ID_Visitante) REFERENCES EQUIPO(ID_Equipo);

ALTER TABLE PARTIDO
ADD FOREIGN KEY (ID_Local) REFERENCES EQUIPO(ID_Equipo);

ALTER TABLE BANEO
ADD FOREIGN KEY (ID_Usuario) REFERENCES USUARIO(ID_Usuario);

ALTER TABLE BANEO
ADD FOREIGN KEY (ID_Amonestacion) REFERENCES AMONESTACION(ID_Amonestacion);

ALTER TABLE PARTIDO_TORNEO
ADD FOREIGN KEY (ID_Partido) REFERENCES PARTIDO(ID_Partido);

ALTER TABLE PARTIDO_TORNEO
ADD FOREIGN KEY (ID_Torneo) REFERENCES TORNEO(ID_Torneo);

ALTER TABLE USUARIO
ADD FOREIGN KEY (Rango) REFERENCES RANGO(ID_Rango);

ALTER TABLE PARTIDO_TORNEO
ADD FOREIGN KEY (ID_Ronda) REFERENCES RONDA(ID_Ronda);

ALTER TABLE EQUIPO_TORNEO
ADD FOREIGN KEY (ID_Torneo) REFERENCES TORNEO(ID_Torneo);

ALTER TABLE EQUIPO_TORNEO
ADD FOREIGN KEY (ID_Equipo) REFERENCES EQUIPO(ID_Equipo);

ALTER TABLE PARTIDO_LIGA
ADD FOREIGN KEY (ID_Partido) REFERENCES PARTIDO(ID_Partido);

ALTER TABLE PARTIDO_LIGA
ADD FOREIGN KEY (ID_Liga) REFERENCES LIGA(ID_Liga);

ALTER TABLE EQUIPO_LIGA
ADD FOREIGN KEY (ID_Equipo) REFERENCES EQUIPO(ID_Equipo);

ALTER TABLE EQUIPO_LIGA
ADD FOREIGN KEY (ID_Liga) REFERENCES LIGA(ID_Liga);

ALTER TABLE USUARIO_EQUIPO
ADD FOREIGN KEY (ID_Equipo) REFERENCES EQUIPO(ID_Equipo);

ALTER TABLE USUARIO_EQUIPO
ADD FOREIGN KEY (ID_Usuario) REFERENCES USUARIO(ID_Usuario);

ALTER TABLE JUEGO
ADD FOREIGN KEY (Tipo) REFERENCES TIPO(ID_Tipo);

CREATE USER IF NOT EXISTS 'master'@'localhost' IDENTIFIED WITH mysql_native_password BY '1234';

GRANT ALL PRIVILEGES ON * . * TO 'master'@'localhost';

FLUSH PRIVILEGES;